---
title: "Diversity in State Legislatures"
author: "Hilary Barker"
date: "10/26/2017"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(corrplot)
source("~/Documents/R Statistical Database/Numerical Ecology with R/NEwR scripts for MacOS/panelutils.R")
library(vegan)

div <- read.csv("state_legislative_diversity.csv")
abbrev_state <- read.csv("state_abbreviations.csv")
```

```{r relationships, include = FALSE, warning = FALSE, message = FALSE}
div2 <- div %>% 
  select(-EDU_NoData, -Pop_female, -NoData_job, -Male) %>% 
  filter(States != "Puerto Rico")

boxplot(div2[ ,-1], use.cols = TRUE)


```

```{r distance, warning = FALSE, message = FALSE, fig.height = 10, fig.width = 10, fig.align = "center", echo = FALSE}
dismat <- as.matrix(vegdist(div2[, -1], method = "euclidean"))

library(colorspace)
# palette <- choose_palette()
palette <- diverge_hcl(16, h = c(260, 0), c = 80, l = c(30, 90), p = 1.5)

heatmap(dismat, col  = palette, labCol = abbrev_state$text, labRow = abbrev_state$text, 
        cexRow = 0.9, cexCol = 0.9)


```


```{r nmds, warning=FALSE, message=FALSE, include = FALSE}
mds <- metaMDS(dismat, k = 2, try = 20, trymax = 20)
mds.point <- as.data.frame(mds$points)
div.vec <- envfit(mds ~ div2$EDU_LessThanBachelors + div2$EDU_Bachelors + div2$EDU_Advanced +
                    div2$Female + div2$Millenials_Gen + div2$GenX_Gen + div2$Boomers_Gen +
                    div2$Silent_Gen + div2$Greatest_Gen + div2$Agriculture + div2$Attorney +
                    div2$BusinessOwner + div2$BusinessOther + div2$Educator +
                    div2$Consult_Nonprofit_Professional + div2$Legislator + div2$Retired +
                    div2$Other_job + div2$NativeAmerican + div2$Asian_PacIsl +
                    div2$Black_AfAmer + div2$Hisp_Latino + div2$Multiracial_Other +
                    div2$Total_minorities + div2$White_Caucasian + div2$Protestant +
                    div2$Catholic + div2$OtherChristian + div2$NonChristian +
                    div2$Unspecified_Religion,
                  permutations = 999, srata = NULL)
# only include significant terms
div.vec2 <- envfit(mds ~ div2$EDU_Advanced +
                    div2$Female + div2$GenX_Gen + div2$Boomers_Gen +
                    div2$Agriculture + div2$Attorney +
                    div2$BusinessOwner +
                    div2$Total_minorities + div2$White_Caucasian + div2$Protestant +
                    div2$NonChristian +
                    div2$Unspecified_Religion,
                  permutations = 999, srata = NULL)

str(div.vec2$vectors$arrows)
dimnames(div.vec2$vectors$arrows)[[1]] <- c("Advanced degree", "Female", "GenX", "Boomers",
                                            "Agriculture", "Attorney", "Business owner", 
                                            "Minorities", "White", "Protestant", 
                                            "Non Christian", "Unspecified religion")
                                            
div2["shannon_index"] <- diversity(div2[ ,-1], index = "shannon", MARGIN = 1)
shan_div <- diversity(div2[ ,-1], index = "shannon", MARGIN = 1)
data.frame((shan_div))
shan_div$State <- div2$States
shan_div$Abbrev <- abbrev_state$text



rbPal <- colorRampPalette(c("red", "blue"))
div_col <- rbPal(10)[as.numeric(cut(shan_div, breaks = 10))]

shan_div2 <- div2 %>% 
  select(States, shannon_index)
shan_div2$Abbrev <- abbrev_state$text
write.csv(shan_div2, "shannon_div_state.csv")

shan_div2 <- arrange(shan_div2, shan_div2$shannon_index)
```


```{r nmds plot, warning = FALSE, message = FALSE, fig.height = 9, fig.width = 10, fig.align = "center", echo = FALSE}

{plot(mds, type = "n") # make an empty NMDS plot
text(mds.point, label = abbrev_state$text, cex = 1.3, col = div_col) # Add the NMDS points for each site
  # and label them as the site number (1-30)
plot(div.vec2, cex = 1, col = rgb(0,0,0, alpha = 0.5))}




```